export const actionTypes = {
  FETCH_BEGIN: 'ENTITIES/FETCH_BEGIN',
  FETCH_SUCCESS: 'ENTITIES/FETCH_SUCCESS',
  FETCH_FAILURE: 'ENTITIES/FETCH_FAILURE',
  DETAIL_BEGIN: 'ENTITIES/DETAIL_BEGIN',
  DETAIL_SUCCESS: 'ENTITIES/DETAIL_SUCCESS',
  DETAIL_FAILURE: 'ENTITIES/DETAIL_FAILURE',
  ADD_BEGIN: 'ENTITIES/ADD_BEGIN',
  ADD_SUCCESS: 'ENTITIES/ADD_SUCCESS',
  ADD_FAILURE: 'ENTITIES/ADD_FAILURE',
  REMOVE_BEGIN: 'ENTITIES/REMOVE_BEGIN',
  REMOVE_SUCCESS: 'ENTITIES/REMOVE_SUCCESS',
  REMOVE_FAILURE: 'ENTITIES/REMOVE_FAILURE',
};
