export const actionTypes = {
  FETCH_SESSION_DETAIL_BEGIN: 'UI/SESSION_DETAIL/FETCH_BEGIN',
  FETCH_SESSION_DETAIL_SUCCESS: 'UI/SESSION_DETAIL/FETCH_SUCCESS',
  FETCH_SESSION_DETAIL_FAILURE: 'UI/SESSION_DETAIL/FETCH_FAILURE',
  DELETE_ATTENDANCE: 'UI/SESSION_DETAIL/DELETE_ATTENDANCE',
};
